version: '2'

services:
  postgresql:
    image: 'bitnami/postgresql:latest'
    environment:
      - POSTGRESQL_USERNAME=bn_moodle
      - POSTGRESQL_DATABASE=bitnami_moodle
      - POSTGRESQL_PASSWORD=your_password
      - ALLOW_EMPTY_PASSWORD=no
    volumes:
      - 'postgresql_data:/bitnami/postgresql'

  moodle:
    image: 'bitnami/moodle:latest'
    environment:
      - MOODLE_DATABASE_HOST=postgresql
      - MOODLE_DATABASE_PORT_NUMBER=5432
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_PASSWORD=your_password
      - ALLOW_EMPTY_PASSWORD=no
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - 'moodle_data:/bitnami/moodle'
    depends_on:
      - postgresql

volumes:
  postgresql_data:
    driver: local
  moodle_data:
    driver: local
