<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 *
 * @property int $username
 * @property int $idnumber
 * @property string $firstname
 * @property string $lastname
 * @property string $middlename
 * @property string $email
 * @property int $confirmed
 *
 *
 **/
class Student extends Model
{
    protected $table = 'm_user';
    public $timestamps = false;
    protected $fillable = [
        'username',
        'idnumber',
        'firstname',
        'lastname',
        'middlename',
        'email',
        'confirmed'
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function (self $student) {
            $student->email = $student->idnumber . '@mamunedu.uz';
            $student->username = $student->idnumber;
            $student->confirmed = 1;
        });
    }
}
